include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_relative_lib_imports: true
    avoid_void_async: true
    avoid_final_parameters: true
    always_use_package_imports: true
    avoid_init_to_null: true
    constant_identifier_names: true
    unawaited_futures: true
    prefer_single_quotes: true
    parameter_assignments: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    require_trailing_commas: true
    use_key_in_widget_constructors: true
