// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY_r9WBr_QOfui39GKjwLr-cRx0gaA8XM',
    appId: '1:643279973445:web:18d70bb986764d56dec72c',
    messagingSenderId: '643279973445',
    projectId: 'helium-edu',
    authDomain: 'helium-edu.firebaseapp.com',
    storageBucket: 'helium-edu.firebasestorage.app',
    measurementId: 'G-5FNS68QLK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm8ZilzevweGPcO8qhzXBo8R3PxgsFEM8',
    appId: '1:643279973445:android:7aa8c18979aa72bedec72c',
    messagingSenderId: '643279973445',
    projectId: 'helium-edu',
    storageBucket: 'helium-edu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59_krBsDsergGBznWfxzjJJot4ZPQl-k',
    appId: '1:643279973445:ios:1fad59583ee04ad2dec72c',
    messagingSenderId: '643279973445',
    projectId: 'helium-edu',
    storageBucket: 'helium-edu.firebasestorage.app',
    androidClientId: '643279973445-fh4qtftlq0gtcktpvt9fhm070p2ik3v3.apps.googleusercontent.com',
    iosClientId: '643279973445-jfl7v2elnh84ld4drtlkekt5b8e5llg0.apps.googleusercontent.com',
    iosBundleId: 'com.heliumedu.heliumapp',
  );

}