# Fastfile for iOS deployment

default_platform(:ios)

platform :ios do
  desc "Upload IPA to TestFlight"
  lane :deploy_testflight do |options|
    ipa_path = options[:ipa_path] || "../build/ios/ipa/heliumedu.ipa"

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_ID']}.p8")
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: ipa_path,
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      distribute_external: false
    )
  end

  desc "Upload IPA to App Store and submit for review"
  lane :deploy_appstore do |options|
    ipa_path = options[:ipa_path] || "../build/ios/ipa/heliumedu.ipa"

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_ID']}.p8")
    )

    upload_to_app_store(
      api_key: api_key,
      ipa: ipa_path,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end
end
