// AUTO-GENERATED — DO NOT EDIT.
// Refreshed periodically from IANA tzdata via:
//   platform/bin/refresh-timezones.py
// IANA release: 2026c

/// IANA link (alias) names mapped to the selectable zone they point at.
///
/// Device APIs report whatever the device is set to without canonicalizing,
/// so a legacy alias will not be found in `TimeZoneConstants.all`.
///
/// Kept out of `time_zone_constants.dart`: the generator unions its output
/// with what is on disk, and would read these back as shipped zones.
class TimeZoneAliases {
  TimeZoneAliases._();

  static const Map<String, String> all = {
    'Africa/Asmera': 'Africa/Nairobi',
    'Africa/Timbuktu': 'Africa/Abidjan',
    'America/Argentina/ComodRivadavia': 'America/Argentina/Catamarca',
    'America/Atka': 'America/Adak',
    'America/Buenos_Aires': 'America/Argentina/Buenos_Aires',
    'America/Catamarca': 'America/Argentina/Catamarca',
    'America/Coral_Harbour': 'America/Panama',
    'America/Cordoba': 'America/Argentina/Cordoba',
    'America/Ensenada': 'America/Tijuana',
    'America/Fort_Wayne': 'America/Indiana/Indianapolis',
    'America/Godthab': 'America/Nuuk',
    'America/Indianapolis': 'America/Indiana/Indianapolis',
    'America/Jujuy': 'America/Argentina/Jujuy',
    'America/Knox_IN': 'America/Indiana/Knox',
    'America/Louisville': 'America/Kentucky/Louisville',
    'America/Mendoza': 'America/Argentina/Mendoza',
    'America/Montreal': 'America/Toronto',
    'America/Nipigon': 'America/Toronto',
    'America/Pangnirtung': 'America/Iqaluit',
    'America/Porto_Acre': 'America/Rio_Branco',
    'America/Rainy_River': 'America/Winnipeg',
    'America/Rosario': 'America/Argentina/Cordoba',
    'America/Santa_Isabel': 'America/Tijuana',
    'America/Shiprock': 'America/Denver',
    'America/Thunder_Bay': 'America/Toronto',
    'America/Virgin': 'America/Puerto_Rico',
    'America/Yellowknife': 'America/Edmonton',
    'Antarctica/South_Pole': 'Pacific/Auckland',
    'Asia/Ashkhabad': 'Asia/Ashgabat',
    'Asia/Calcutta': 'Asia/Kolkata',
    'Asia/Choibalsan': 'Asia/Ulaanbaatar',
    'Asia/Chongqing': 'Asia/Shanghai',
    'Asia/Chungking': 'Asia/Shanghai',
    'Asia/Dacca': 'Asia/Dhaka',
    'Asia/Harbin': 'Asia/Shanghai',
    'Asia/Istanbul': 'Europe/Istanbul',
    'Asia/Kashgar': 'Asia/Urumqi',
    'Asia/Katmandu': 'Asia/Kathmandu',
    'Asia/Macao': 'Asia/Macau',
    'Asia/Rangoon': 'Asia/Yangon',
    'Asia/Saigon': 'Asia/Ho_Chi_Minh',
    'Asia/Tel_Aviv': 'Asia/Jerusalem',
    'Asia/Thimbu': 'Asia/Thimphu',
    'Asia/Ujung_Pandang': 'Asia/Makassar',
    'Asia/Ulan_Bator': 'Asia/Ulaanbaatar',
    'Atlantic/Faeroe': 'Atlantic/Faroe',
    'Atlantic/Jan_Mayen': 'Europe/Berlin',
    'Australia/ACT': 'Australia/Sydney',
    'Australia/Canberra': 'Australia/Sydney',
    'Australia/Currie': 'Australia/Hobart',
    'Australia/LHI': 'Australia/Lord_Howe',
    'Australia/NSW': 'Australia/Sydney',
    'Australia/North': 'Australia/Darwin',
    'Australia/Queensland': 'Australia/Brisbane',
    'Australia/South': 'Australia/Adelaide',
    'Australia/Tasmania': 'Australia/Hobart',
    'Australia/Victoria': 'Australia/Melbourne',
    'Australia/West': 'Australia/Perth',
    'Australia/Yancowinna': 'Australia/Broken_Hill',
    'Brazil/Acre': 'America/Rio_Branco',
    'Brazil/DeNoronha': 'America/Noronha',
    'Brazil/East': 'America/Sao_Paulo',
    'Brazil/West': 'America/Manaus',
    'CET': 'Europe/Brussels',
    'CST6CDT': 'America/Chicago',
    'Canada/Saskatchewan': 'America/Regina',
    'Canada/Yukon': 'America/Whitehorse',
    'Chile/Continental': 'America/Santiago',
    'Chile/EasterIsland': 'Pacific/Easter',
    'Cuba': 'America/Havana',
    'EET': 'Europe/Athens',
    'EST': 'America/Panama',
    'EST5EDT': 'America/New_York',
    'Egypt': 'Africa/Cairo',
    'Eire': 'Europe/Dublin',
    'Europe/Belfast': 'Europe/London',
    'Europe/Kiev': 'Europe/Kyiv',
    'Europe/Nicosia': 'Asia/Nicosia',
    'Europe/Tiraspol': 'Europe/Chisinau',
    'Europe/Uzhgorod': 'Europe/Kyiv',
    'Europe/Zaporozhye': 'Europe/Kyiv',
    'GB': 'Europe/London',
    'GB-Eire': 'Europe/London',
    'HST': 'Pacific/Honolulu',
    'Hongkong': 'Asia/Hong_Kong',
    'Iceland': 'Africa/Abidjan',
    'Iran': 'Asia/Tehran',
    'Israel': 'Asia/Jerusalem',
    'Jamaica': 'America/Jamaica',
    'Japan': 'Asia/Tokyo',
    'Kwajalein': 'Pacific/Kwajalein',
    'Libya': 'Africa/Tripoli',
    'MET': 'Europe/Brussels',
    'MST': 'America/Phoenix',
    'MST7MDT': 'America/Denver',
    'Mexico/BajaNorte': 'America/Tijuana',
    'Mexico/BajaSur': 'America/Mazatlan',
    'Mexico/General': 'America/Mexico_City',
    'NZ': 'Pacific/Auckland',
    'NZ-CHAT': 'Pacific/Chatham',
    'Navajo': 'America/Denver',
    'PRC': 'Asia/Shanghai',
    'PST8PDT': 'America/Los_Angeles',
    'Pacific/Enderbury': 'Pacific/Kanton',
    'Pacific/Johnston': 'Pacific/Honolulu',
    'Pacific/Ponape': 'Pacific/Guadalcanal',
    'Pacific/Samoa': 'Pacific/Pago_Pago',
    'Pacific/Truk': 'Pacific/Port_Moresby',
    'Pacific/Yap': 'Pacific/Port_Moresby',
    'Poland': 'Europe/Warsaw',
    'Portugal': 'Europe/Lisbon',
    'ROC': 'Asia/Taipei',
    'ROK': 'Asia/Seoul',
    'Singapore': 'Asia/Singapore',
    'Turkey': 'Europe/Istanbul',
    'US/Aleutian': 'America/Adak',
    'US/East-Indiana': 'America/Indiana/Indianapolis',
    'US/Indiana-Starke': 'America/Indiana/Knox',
    'US/Michigan': 'America/Detroit',
    'US/Samoa': 'Pacific/Pago_Pago',
    'W-SU': 'Europe/Moscow',
    'WET': 'Europe/Lisbon',
  };
}
