name: "CI/CD"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 9.x
        uses: actions/setup-node@v1
        with:
          node-version: 9.x
      - name: Install dependencies
        run:
          make build
      - name: Run tests
        run:
          make test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          directory: ./_build/coverage
