name: "Build"

run-name: "Build ${{ github.ref_name }}"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Install dependencies
        run:
          make install build
      - name: Run tests
        run:
          make test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          directory: ./_build/coverage
